name = "oshi-link"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "oshi-link-db"
database_id = "48e42e89-7a9e-485e-82d2-a1f20e53d88e"

